### PR TITLE
Fix laziness test for LazyList

### LINKED ISSUE #308: StrawmanTest.mainTest failing in Scala 2.13.0-M3
```
[collection-strawman] [error] Test strawman.collection.test.StrawmanTest.mainTest failed: java.lang.AssertionError: assertion failed, took 0.472 sec
[collection-strawman] [error]     at scala.Predef$.assert(Predef.scala:204)
[collection-strawman] [error]     at strawman.collection.test.StrawmanTest.lazyListOps(Test.scala:466)
[collection-strawman] [error]     at strawman.collection.test.StrawmanTest.mainTest(Test.scala:576)
[collection-strawman] [error]     ...
```

details at https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/856/consoleFull

doesn't seem to be intermittent (failed in both runs last night)

### PR DESCRIPTION
**Pull request by julienrf**
Fixes #308.

I’ve also renamed `lazyAppendAll` to `lazyAppendedAll` but the important part of the PR is in the test file.

The new test passes only on 2.13, though, not on 2.12 nor dotty.

### CODE REVIEW

**Comment by SethTisue** [comment]
rebase?

**Comment by szeiger** [comment]
How about putting it into a separate test file under `scala_2.13`?

**Comment by julienrf** [comment]
I’ve changed the scala version to 2.13.0-pre-54f909e to not get compilation errors (so that we can move forward).

**Comment by julienrf** [comment]
So, now the issue is that there is no Scala.js compiler for the custom Scala version I’m using.

We can not update to M3. I suggest that we come back to this PR after we have moved to scala/scala.

**Comment by szeiger** [comment]
@julienrf Is 2.13.0-pre-54f909e before or after M3?

**Comment by julienrf** [comment]
It was before: https://github.com/scala/scala/commit/54f909e6a29508067040750b59270e32a991b31d

**Comment by szeiger** [comment]
OK, since https://github.com/scala/bug/issues/10736 has been fixed I'm marking this as not relevant for the move to scala/scala. We should make the changes afterwards when we no longer need ScalaJS.

**Comment by julienrf** [comment]
Ported to scala/scala as https://github.com/scala/scala/pull/6509 and https://github.com/scala/scala/pull/6510

**Pull request closed without merging**
