### PR TITLE
Add the `splitWith` operation to SeqDecorator

### PR DESCRIPTION
**Pull request by markus1189**
Relates to #241. This pull request adds the first of the two proposed methods.

There is still some bikeshedding to do before merging, I will comment when it's ready, but please comment!

Greetings from the Scala Center FLOSS Spree at Scala.io 2017!

### CODE REVIEW

**Comment by markus1189** [comment]
Okay I updated the pr, ready for comments.  The things I don't like:

1) we have to duplicate the Generators in the test because the `scalacheck` subproject does not cross-compile

2) `splitWith` currently works only for `Seq` types, it would be nice if for example `String` would be supported as well

**Comment by julienrf** [comment]
Thanks @markus1189! I’ll try to find some time to address the issues you raised.

**Comment by markus1189** [comment]
@julienrf I'm happy to do more work as well, If you could give me some pointers

**Comment by julienrf** [comment]
The decorator doesn’t work on `String` values for two reasons:
- `String` is not a collection, it needs to be implicitly converted to a `StringView` to become a collection, but since our decorators also require an implicit conversion to be applied, we have to apply two implicit conversions in a row, which is disallowed by the type system. We could circumvent this issue by taking the implicit conversion to a collection as an implicit parameter of the implicit conversion to the decorator.
- `StringView` doesn’t conform to the upper bound of the `SeqDecorator` implicit conversion parameter type: `CC[X] <: SeqOps[A, CC, _]`. `StringView` is an `IndexedView[Char]`, which is a `SeqOps[Char, View, _]` (whereas we need it to be a `SeqOps[Char, IndexedView, _]`).

**Pull request closed without merging**
