### PR TITLE
Immutable arrays

### PR DESCRIPTION
**Pull request by julienrf**
This is a rebased version of #6 with benchmarks.

### CODE REVIEW

**Comment by julienrf** [comment]
Here are some charts generated by the benchmarks:

lookup

Random access can be up to 2x faster than `Vector` (and an order of magnitude faster than `List`, of course).

concat

Concatenation can be up to 10x faster than `Vector` and `List`.

map

`map` can be up to 3x faster than `Vector` and 5x faster than `List`.

uncons

`tail` is an order of magnitude slower than `Vector` or `List`.

**Comment by julienrf** [comment]
@odersky @Ichoran @szeiger There is a non anecdotal design decision behind this PR: generic collection types (e.g. `Iterable`, `Seq`, `Set`, etc.) have no implemented operations. The idea is to avoid inheriting inefficient operations. Concrete collection types can still mix in “default” implementations by mixing in traits like `IterableMonoTransformsFromIterable` (which implements operations of `IterableMonoTransforms` on top of a `fromIterable(it: Iterable[A]): Repr` method).

Do you like this idea?

**Comment by Ichoran** [comment]
I like the idea of having a way to avoid pulling in inefficient methods, so overall yes.  I'm not sure the number of methods should be literally _zero_ since there is sometimes only one right way to do things.  On the other hand, if the set of implementations is not very granular, it doesn't matter because usually you will want _something_ and so it's tempting to just pull in everything.  This is harder to notice at this stage of the strawman because the set of methods is not very complete.

**Comment by szeiger** [comment]
It would be helpful to take a step back and look for who overwrites what in the current collection implementations. `fromIterable` may still end up being the best default, or at least the only generic implementation that can be reused by multiple collection types.

**Comment by julienrf** [comment]
Superseeded by #87

**Pull request closed without merging**
