### PR TITLE
Implement method `groupBy` and alternative version `viewBy`

### PR DESCRIPTION
**Pull request by LPTK**
See issue #42.

### CODE REVIEW

**Comment by julienrf** [comment]
Hi @LPTK!

Sorry for the delay, I was busy on other things, but `groupBy` is one of the next things to do, now that `Map`s are implemented (well, we still miss mutable `Map`s), so I think it’s time to review this PR.

The numbers you posted in #42 are nice but there are several differences between `viewBy` and `groupBy`. I think that would be interesting to know the performance improvement brought by each change.

Also, in the discussion of #42, we mentioned another variant that performs an aggregation operation on each group. I think it would be nice to include it. And we should try your suggestion that consists of adding a new parameter to `groupBy` but with a default value to not break source compatibility.

Finally, there are still some discussion points:

- What should be the type of the collection returned by `groupBy`? A `Map[K, ?]`, an `Iterable[(K, ?)]` or the same collection type? I don’t think returning the same collection type would make sense, especially with ordered collections, I have a slight preference for returning `Map`, though I would be interested in knowing precisely if it has a cost over returning an `Iterable`.
- What should be the type of the groups? Here I think it makes sense to keep the same collection type (again, think of ordered collections).

So, my preference would be to have something like so:

~~~ scala
trait IterableOps[+A] {
  def groupAndAggregate[K, V](key: A => K, value: A => V, aggregate: (V, V) => V): Map[K, V]
}

trait IterablePolyTransforms[+A, +C[X]] {
  def groupBy[K, V](key: A => K, value: A => V = a => a): Map[K, C[V]]
}
~~~

What do you think? Would you be interested in working on that, @LPTK?

**Comment by Ichoran** [comment]
`groupBy`'s use-case signature should not change.  If we want something similar that retains the original collection type we should give it a new name (e.g. `mapGroups(key: A => K)(f: (K, CC[A]) => B): CC[B]`).

**Comment by julienrf** [comment]
@LPTK What’s the status of this PR?

**Comment by LPTK** [comment]
@julienrf I think this was more or less superseded by https://github.com/scala/collection-strawman/pull/253, so I'm closing.

**Pull request closed without merging**
