### PR TITLE
Fix empty iterator in NumericRange

### PR DESCRIPTION
**Pull request by marcelocenerine**
Fix for #265

### CODE REVIEW

**Comment by Ichoran** [comment]
I don't understand what the problem was with the old logic.  Can you figure it out?  The new approach seems like it would perform more poorly, and if the old approach didn't work, there was probably something else wrong which is still wrong and is a bug.

In particular, the iterator has to detect _anyway_ when it becomes empty, so if it starts off empty it should be able to start in that state, not have to return an entirely different iterator type (i.e. Iterator.empty).  Yes, there's an advantage in memory allocation from returning `Iterator.empty`, but it's probably more than offset by needing multiple dispatch on the iterator.

**Comment by marcelocenerine** [comment]
@Ichoran, the problem was that the old logic calls `last` when instantiating `NumericRangeIterator`:

```scala
override def iterator(): Iterator[T] = new NumericRangeIterator[T](start, step, last, isEmpty)

override def last: T =
  if (length == 0) Nil.head
  else locationAfterN(length - 1)
```

Another option would be to turn `lastElement` a by-name parameter of the `NumericRangeIterator` constructor. It is accompanied by the `initiallyEmpty` flag which is checked first and would avoid the exception.

**Comment by Ichoran** [comment]
What about `if (isEmpty) NumericRangeIterator(start, step, start, false) else NumericRangeIterator(start, step, last, true)` or something like that?

**Comment by marcelocenerine** [comment]
@Ichoran, that would work too. However, I'm not seeing much advantage compared to the 1st approach, given that with your suggestion both `iterator()` and `NumericRangeIterator(...)` would have to concern about the initial empty state rather than just one.
The 1st solution does not perform more poorly given that the old approach calls `Nil.head`, which is the source of the problem. In the 2nd solution (by-name parameter) there wouldn't be an additional dispatch given that the function wrapping the parameter would never be called (although it needs to be created). This shouldn't be a big deal as it only happens when the iterator is created. Both 1 & 2 look more readable too.
I'm OK with your approach too. Just wanted to share my thoughts.

**Comment by marcelocenerine** [comment]
Alternatively....

```scala
  self =>

   override def iterator() = new Iterator[T] {
    private var _hasNext = !self.isEmpty
    private var _next: T = start
    private val lastElement: T = if (_hasNext) last else start
    def hasNext: Boolean = _hasNext
    def next(): T = {
      if (!_hasNext) Iterator.empty.next()
      val value = _next
      _hasNext = value != lastElement
      _next = num.plus(value, step)
      value
    }
  }
```

**Comment by marcelocenerine** [comment]
@Ichoran I changed to the approach above which is similar to what you proposed, but having the emptiness dealt with in one single place.

**Comment by Ichoran** [comment]
LGTM, thanks @marcelocenerine !

**Pull request merged**
