### PR TITLE
Laziness tweaks

### PR DESCRIPTION
**Pull request by pnf**
Make `LazyList.#::`'s argument non-lazy, as it will actually be evaluated eagerly; add a truly lazy `prepend` method.
Somewhat related: stub out `View.toString` so views don't get forced prematurely.

### CODE REVIEW

**Comment by julienrf** [comment]
@SethTisue Do you think we could fix the issue in scalac 2.13?

**Comment by julienrf** [comment]
If the issue can not be resolved in the compiler, then we should use the same workaround as we use in the current `Stream` collection, as noted by @szeiger in #127.

**Comment by pnf** [comment]
I changed it to use a `Stream`-like implicit trick and added the classic Fibonacci example (which now works) to the tests as well.  It's a bit irritating that the first element is still strict, but this applies to `Stream` as well.

**Comment by pnf** [comment]
So, the bad news is that the new tests don't pass with dotty.  The even worse news is that they don't pass under dotty even with `scala.collection.immutable.Stream`...

**Comment by julienrf** [comment]
What if you explicitly instantiate the correct type of elements? `List[BigInt](0, 1, 1, 2)`

**Comment by julienrf** [comment]
Hey @pnf, we discussed this issue and came to the conclusion that we should not have lazy right-associative operators unless they are properly supported by the language.

Consequently, we should remove the `#::` and just have a `prepend` method on `LazyList`.

**Comment by julienrf** [comment]
@pnf I think we should completely remove the `#::` operator (and rename the homonym extractor). The workaround that relies on an wrapping class is only partially lazy.

**Comment by pnf** [comment]
@julienrf I'm not so sure... The `#::` operator is "sufficiently lazy" as to be useful for `Stream`, where it gets extensive use in real code, and it could be made genuinely lazy with a little compiler work. 
That said, I'm unclear on whether `LazyList` is intended to replace `Stream` or to supplement it, and, if the latter, why one would choose one over the other.

**Comment by julienrf** [comment]
`LazyList` replaces `Stream`.

I really dislike having an `#::` operator that’s only partially lazy. I think that could lead to very confusing situations. I prefer the semantics of operations on `LazyList` to be clearly always lazy excepted for “terminal” operations (like `fold`).

**Comment by pnf** [comment]
It seems like there are a few probable routes by which it would become fully lazy by the time the new collections are stable: eg.the underlying SI might be fixed, or we may be able to use scalameta. If LL is to replace Stream and we remove the right-associative syntax, the message to users is that we're removing functionality they use, for their own good, because of a bug in another part of the ecosystem that we don't feel like addressing (for some meaning of "we").

**Comment by julienrf** [comment]
Alright, that’s good for now, could you please squash your commits into a single one?

**Comment by julienrf** [comment]
Thanks @pnf, I squashed your commits and merged them to master: https://github.com/scala/collection-strawman/commit/950e7ddb432e0d1e1ebff34d292ff457908e07ba

**Pull request closed without merging**
