### PR TITLE
upgrade Scala 2.13 version to 2.13.0-M3

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by julienrf** [comment]
Looks like we should merge #361 or #345 before :)

**Comment by SethTisue** [comment]
ah right, #308

**Comment by julienrf** [comment]
Now that #361 has been merged I’ve run again the CI on this PR and we have a different error:

~~~
[error] /home/travis/build/scala/collection-strawman/collections-contrib/src/test/scala/strawman/collection/decorators/MapDecoratorTest.scala:12: Cannot construct a collection of type C with elements of type (Int, String) based on a collection of type stabilizer$1.this.type.
[error]     val zipped = map1.zipByKeyWith(map2)(_ ++ _)
[error]                                         ^
~~~

For some reason the compiler is unable to pick the right implicit `BuildFrom`. This was working in 2.13.0-M2.

**Comment by julienrf** [comment]
With `-Xlog-implicits` I get the following message:

~~~
[info] /home/julien/workspace/dev/scala/collection-strawman/collections-contrib/src/test/scala/strawman/collection/decorators/MapDecoratorTest.scala:12: collection.this.BuildFrom.buildFromMapOps is not a valid implicit value for strawman.collection.BuildFrom[stabilizer$1.this.type,(Int, String),C] because:
[info] hasMatchingSymbol reported error: polymorphic expression cannot be instantiated to expected type;
[info]  found   : [CC[X, Y] <: strawman.collection.Map[X,Y] with strawman.collection.MapOps[X, Y, CC, _], K0, V0, K, V]strawman.collection.BuildFrom[CC[K0,V0],(K, V),CC[K,V]]
[info]  required: strawman.collection.BuildFrom[stabilizer$1.this.type,(Int, String),C]
[info]     val zipped = map1.zipByKeyWith(map2)(_ ++ _)
[info]                                         ^
~~~

However, this candidate should match. And if I explicitly supply it like the following it compiles:

~~~ scala
val zipped = map1.zipByKeyWith(map2)(_ ++ _)(BuildFrom.buildFromMapOps)
~~~

**Comment by SethTisue** [comment]
rebased

**Comment by julienrf** [comment]
Is it possible for you to investigate the regression in the implicit search or do you want me to minimize the test case?

**Comment by julienrf** [comment]
Maybe scala/scala#6308 would be the culprit?

**Comment by julienrf** [comment]
I’ve created https://github.com/scala/bug/issues/10736 to keep track of the regression.

**Comment by julienrf** [comment]
I’m closing this PR. The changes made here have been replicated in #345 and adapted a bit to not use M3 but a prior scala version that doesn’t produce compilation errors.

**Pull request closed without merging**
