### PR TITLE
Add support to compile with dotty

### PR DESCRIPTION
**Pull request by biboudis**
Enables support to compile with dotty (thx @liufengyun for the tip)

@julienrf WDYT?

### CODE REVIEW

**Comment by smarter** [comment]
I'm about to completely rewrite sbt-dotty to make cross-compilation much easier, so I wouldn't merge this now.

**Comment by biboudis** [comment]
Sure, NP! @julienrf feel free to close it and if you would agree we can make a note with this workaround somewhere, for anyone wanting to play with dotty & strawman until the sbt-dotty update!

Thx @smarter

**Comment by julienrf** [comment]
Thanks @biboudis.

I suggest to wait for @smarter’s changes.

**Comment by julienrf** [comment]
Also, the CI does not know how to resolve dotty. I guess we will have to upgrade the environment in which travis-ci runs. Unless there are some public releases of dotty (@smarter?).

**Comment by SethTisue** [comment]
> I guess we will have to upgrade the environment in which travis-ci runs

can't we just add a resolver in build.sbt?

**Comment by smarter** [comment]
Dotty nightlies are published to maven central: https://repo1.maven.org/maven2/ch/epfl/lamp/dotty_2.11/

**Comment by biboudis** [comment]
Will turn green after #59 gets merged! 

Cheers!

**Pull request merged**
